travis:
  secure:
    BINSTAR_TOKEN: lTddrF6sAhb6i0noEDKhonE1gR6/vFofMnz1T5QnV4IRfI+E6xGh1aGmH+S3GGM+Jlgp8WLFYPIDhNiUUVR6ObESW9Tt4jV9PGFaCJx0t95o+Fne2AFQguKmq2ylGPFPQVcK8HperwN1NvuBheiod4elaTeyLUJ+KM2KzK/7dnaS4z/KaKGIK7r8P9dHdEQxDub8Mvjiv0U68chVM9OueG6LszL/4Un4hel2aeRAwXLM9IhQfq358hk9sKkv4f9kV2pc5xMUa/0E5VnRV+t0gMbGddYRmGLwRg0Ti2WmLa8NttkcHFkg1a4c0/TvPggK1blNFB7oEoNcztaa9v8pu73RL/fnMJFsM0xgbeuwePQUIwJqnPTScU+5YL8Pblf/XQc/qFsLp93GBfHdol5JJenGIInfXKZHnIYe5YH6xOCsrCEdiVZwmP+fvDCE1KFN+cXGnd1NsZAYHpKzW1G4f20VAIEpTlOKjWrTbMQ8ixQx5CN2Bxj2CnTwZngO9+Dh8KUHaKTjURRNim8oM+GWM4WEtW2PWE1ybKACCTTkNbva/hcNwAe0cLBZWGBcz2qUo5SM1+uYzE1a89IkRelv2TQrnTLaZfmO34LFrX2Zas4be7agR0gPGy8mRMmgHJ4HayO3HRWaZA6LzmUUavyzQG+M4tF9fobxNXuX4KA3lQw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
